import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import TanstackProviders from "./providers/tanstackProviders";
import { cn } from "@/lib/utils";
import { redirect } from "next/navigation";
import { useMe } from "@/features/auth/hooks/useme";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", inter.className, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <TanstackProviders>
          <main>
            <TooltipProvider>
              {children}
            </TooltipProvider>
          </main>
          <Toaster />
        </TanstackProviders>
      </body>
    </html>
  );
}
